# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']

    #spool: { type: 'memory' }

    url: '%env(MAILER_URL)%'
    #delivery_addresses: ['smaglione@mandint.org']
