# FOSUserBundle Configuration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    App\Entity\Gui\User
    group:
        group_class: App\Entity\Gui\Group
    from_email:
        address: "testapp@testapp.com"
        sender_name: "Test App"
    