framework:
    secret: '%env(APP_SECRET)%'
    translator:      { fallback: '%locale%' }
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 2400

    #esi: true
    #fragments: true
    php_errors:
        log: true

    templating:
        engines: ['twig','php']


