services:
    _defaults:
        public: true

    test.App\Service\UserManagement: '@App\Service\UserManagement'

    test_alias.swiftmailer.mailer:
        alias: 'swiftmailer.mailer'
        public: true

