# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    keyrock.app.id: '%env(KEYROCK_APP_ID)%'
    keyrock.admin.user: '%env(KEYROCK_ADMIN_USER)%'
    keyrock.admin.password: '%env(KEYROCK_ADMIN_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # App\Controller\SecurityController:
    #     decorates: fos_user.security.controller

    SunCat\MobileDetectBundle\DeviceDetector\MobileDetector: '@mobile_detect.mobile_detector.default'

    Symfony\Component\Translation\DataCollectorTranslator: '@translator.data_collector'

    Symfony\Component\HttpKernel\DataCollector\RequestDataCollector: '@data_collector.request'

    Symfony\Component\Security\Core\Encoder\EncoderFactory: '@security.encoder_factory.generic'

    # FOS\UserBundle\Doctrine\UserManager: '@fos_user.user_manager.default'

    # App\Security\FOSUBUserProvider:
    #     arguments: ['@fos_user.user_manager',{fiware: fiware_id}] 

    Http\Client\Common\HttpMethodsClient: '@httplug.client.app.http_methods'

    


    


        
   